name: MunshiG
description: A new Flutter application.
publish_to: none
version: 1.1.0+5

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  country_pickers: ^2.0.0
  device_info_plus: ^7.0.1
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_email_sender: ^5.1.0
  flutter_getit: ^1.2.1
  flutter_image_compress: ^1.1.3
  flutter_svg: ^1.1.5
  fluttertoast: ^8.1.1
  image_picker: ^0.8.6
  intl: ^0.17.0
  material_design_icons_flutter: ^5.0.6996
  nepali_date_picker: ^5.3.0
  nepali_utils: ^3.0.3
  package_info_plus: ^3.0.1
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  excel:
    git:
      url: https://github.com/justkawal/excel
      ref: null-safety
  progress_dialog:
    git:
      url: https://github.com/Rishan99/progress-dialog
      ref: main
  provider: ^6.0.4
  sembast: ^3.3.1
  sleek_circular_slider: ^2.0.1
  syncfusion_flutter_xlsio: ^20.3.50-beta

dev_dependencies:
  build_runner: ^2.3.2
  flutter_test:
    sdk: flutter
  json_serializable: ^6.5.3

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/language/
    - fonts/

  fonts:
    - family: FontAwesomeBrands
      fonts:
        - asset: assets/FontAwesome5_Brands.ttf
    - family: FontAwesomeRegular
      fonts:
        - asset: assets/FontAwesome5_Regular.ttf
    - family: FontAwesomeSolid
      fonts:
        - asset: assets/FontAwesome5_Solid.ttf
    - family: SourceSansPro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf
        - asset: fonts/SourceSansPro-Italic.ttf
          style: italic
        - asset: fonts/SourceSansPro-Black.ttf
          weight: 900
        - asset: fonts/SourceSansPro-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: fonts/SourceSansPro-Bold.ttf
          weight: 700
        - asset: fonts/SourceSansPro-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/SourceSansPro-ExtraLight.ttf
          weight: 200
        - asset: fonts/SourceSansPro-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/SourceSansPro-Light.ttf
          weight: 300
        - asset: fonts/SourceSansPro-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/SourceSansPro-SemiBold.ttf
          weight: 600
        - asset: fonts/SourceSansPro-SemiBoldItalic.ttf
          weight: 600
          style: italic
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
