name: MunshiG
description: A new Flutter application.

version: 1.0.1+2

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  country_pickers: ^1.1.0
  excel: ^1.0.3
  flutter_email_sender: ^3.0.1
  flutter_svg: ^0.17.4
  image_picker: ^0.6.7+4
  intl: ^0.16.1
  nepali_date_picker: ^4.1.0
  package_info: ^0.4.1
  path_provider: ^1.6.24
  # fl_chart: ^0.12.0
  permission_handler: ^5.0.1+1
  provider: ^2.0.0+1
  sembast: ^1.15.4
  sleek_circular_slider: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.4.0
  json_serializable: ^2.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: FontAwesomeBrands
      fonts:
        - asset: assets/FontAwesome5_Brands.ttf
    - family: FontAwesomeRegular
      fonts:
        - asset: assets/FontAwesome5_Regular.ttf
    - family: FontAwesomeSolid
      fonts:
        - asset: assets/FontAwesome5_Solid.ttf
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
